### ISSUE TITLE
Crashing in Ruby 2.6.3

### ISSUE THREAD

**Issue by Lewiscowles1986** [teoljungberg/minitest-documentation#4]
Getting the following bug

```
Traceback (most recent call last):
        4: from /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:63:in `block in autorun'
        3: from /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:134:in `run'
        2: from /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:791:in `start'
        1: from /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:791:in `each'
/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:701:in `start': private method `puts' called for nil:NilClass (NoMethodError)
rake aborted!
```

**Comment by Lewiscowles1986** [comment]
Closing as pointing the `Gemfile` to use github @ master branch latest commit fixed

```Gemfile
# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

group :test do
  gem "byebug"
  gem "simplecov"
  gem "minitest-documentation", "~> 1.0", github: "teoljungberg/minitest-documentation",
                                          ref: '4f3e489b312b7bd7ebc4a9c2a4d7f1fa80ef697e'
  gem "rake", "~> 12.3"
end

```
